name: Build and Release Windows Installer

on:
  push:
    branches: [ main, master, ci-test ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    if: github.event.head_commit.author.name != 'github-actions[bot]'
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout latest commit from master
        uses: actions/checkout@v3
        with:
          ref: master  # On force le checkout sur la branche master
          fetch-depth: 0  # Permet d'avoir l'historique complet des commits pour éviter les conflits

      - name: Display latest commit
        run: git log --oneline -n 5

      - name: Generate tag name
        id: tag
        run: echo "TAG=$(date +'%y.%m.%d').${{ github.run_number }}" >> $GITHUB_ENV

      - name: Display version
        run: |
          echo "Version extraite: ${{ env.TAG }}"

      - name: Update VERSION in config.h
        run: |
          sed -i 's/#define VERSION.*/#define VERSION "${{ env.TAG }}"/' config.h
        shell: bash

      - name: Commit updated version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add config.h
          git commit -m "Update version to ${{ env.TAG }}"
          git push

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'  # ⚠️ Change cette version selon celle que tu utilises
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'
          cache: true

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Project
        run: |
          qmake
          mingw32-make

      - name: Deploy Application with windeployqt
        run: |
          windeployqt --verbose=2 bin/SavvyCAN.exe

      - name: List files in bin before Inno Setup
        run: |
          echo "Listing files in bin/ directory..."
          Get-ChildItem -Path bin/ -Recurse

      - name: Build Installer with Inno Setup
        run: |
          echo "Using version: ${{ env.TAG }}"
          if (-not "${{ env.TAG }}") { 
            echo "ERROR: VERSION is empty!"
            exit 1 
          }
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "/DMyAppVersion=${{ env.TAG }}" "setup.iss"

      - name: Upload Installer to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.TAG }}"
          name: "Release v${{ env.TAG }}"
          files: ./Output/SavvyCAN_${{ env.TAG }}_Setup.exe