name: Build and Release Windows Installer

on:
  push:
    tags:
      - 'v*'  # Déclenche le workflow uniquement lorsqu'un tag versionné est poussé

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'  # ⚠️ Change cette version selon celle que tu utilises
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'
          cache: true

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Extract version from tag
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build Installer with Inno Setup
        run: |
          echo "Using version: ${{ env.VERSION }}"
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "/DMyAppVersion=${{ env.VERSION }}" "setup.iss"

      - name: Build Project
        run: |
          qmake
          mingw32-make

      - name: Deploy Application with windeployqt
        run: |
          windeployqt --verbose=2 bin/SavvyCAN.exe

      

      - name: Upload Installer to Release
        uses: softprops/action-gh-release@v1
        with:
          files: SavvyCAN_Setup.exe
          token: ${{ secrets.GITHUB_TOKEN }}